routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()){
        return redirect('home');
    }
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/productos/proveedor/{id}', 'ProductoController@getProductosDeProveedor')->name('productosProveedor');
    Route::get('/productos/categoria/{id}', 'ProductoController@getProductosDecategoria')->name('prodCategoria');
    Route::resource('proveedores', 'ProveedorController');
    Route::resource('productos', 'ProductoController');
    Route::resource('categorias', 'CategoriaController');
    Route::resource('clientes', 'ClienteController');
    Route::resource('repartidores', 'RepartidorController');
    Route::resource('pedidos', 'PedidosController');
    Route::get('categoria/del/{id}', 'CategoriaController@destroy')->name('delCat');
    Route::get('proveedor/del/{id}', 'ProveedorController@destroy')->name('delProveedor');
    Route::get('cliente/del/{id}', 'ClienteController@destroy')->name('delCliente');
    Route::get('/producto/del/{id}', 'ProductoController@destroy')->name('delProd');
    Route::get('repartidor/del/{id}', 'RepartidorController@destroy')->name('delRepartidor');

    Route::get('repartidor/albaranes/{id}', 'RepartidorController@pdf')->name('albaranesRepartidor');


    Route::post('/admin/updateEmail/{id}', 'HomeController@updateEmail')->name('updateEmail');
    Route::get('/admin/updateEmail', 'HomeController@edit')->name('editAdmin');
    Route::post('/admin/updatePassword/{id}', 'HomeController@updatePassword')->name('updatePassword');
    Route::get('/admin/updatePassword', 'HomeController@editPassAdmin')->name('editPassword');

    //Route::get('/pedidos', 'PedidosController@index')->name('pedidos');
    //Route::get('/pedido/{id}', 'PedidosController@show')->name('pedido');
    Route::get('/pedido/cliente/{id}', 'PedidosController@pedidosDeCliente')->name('pedidosCliente');

    Route::get('graficas', 'UserChartController@index')->name('graficas');


});

Route::get('storage/{userid}/{filename}', function ($userid, $filename) {
    return Storage::get('producto'.$userid . '/' . $filename);
});

resources/views/addProducts.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>AÑADIR PRODUCTO</h1>
        <hr>
        @if (sizeof($proveedores) != 0 && sizeof($categorias) != 0)
            <form action={{route('productos.store')}} method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre Producto </label>
                    <input type="text" required class="form-control" id="nombre" name="nombre"
                           aria-describedby="emailHelp"
                           placeholder="Nombre Prodcuto">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Precio</label>
                    <input type="number" required min="0" step="0.01" class="form-control" id="precio"
                           name="precio" placeholder="Precio">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Unidades</label>
                    <input type="number" required min="0" step="1" class="form-control" id="unidades"
                           name="unidades" placeholder="Unidades">
                </div>
                <div class="form-group ">
                    <label for="proveedor_id">Proveedor</label>
                    <select id="proveedor_id" name="proveedor_id" class="form-control">
                        <option selected>Escoger uno</option>
                        @foreach ($proveedores as $proveedor)
                            <option value= {{$proveedor->id}} >{{$proveedor->nombre." ".$proveedor->apellidos}} </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group ">
                    <label for="categoria_id">Categoria</label>
                    <select id="categoria_id" name="categoria_id" class="form-control">
                        <option selected>Escoger una</option>
                        @foreach ($categorias as $categoria)
                            <option value= {{$categoria->id}} >{{$categoria->nombre}} </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <input type="file" accept="image/*" id="photo_id" name="imagen" class="form-control-file"
                           id="exampleFormControlFile1">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Añadir Producto</button>
            </form>
            <hr>
        @else
            <p>Antes de añadir productos, debes de tener proveedores y categorias en la base de datos.</p>
        @endif
            <form action={{route('home')}} method="GET">
                <button type="submit" class="btn btn-secondary mb-2">MENU</button>
            </form>

    </div>
@endsection

resources/views/addRepartidor.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>AÑADIR REPARTIDOR</h1>
        <hr>
        <form action={{route('repartidores.store')}} method="POST">
            @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Nombre </label>
                <input type="text" required class="form-control" id="nombre" name="nombre" aria-describedby="emailHelp"
                       placeholder="Nombre">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">EMAIL</label>
                <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp"
                       placeholder="EMAIL">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">CONTRASEÑA</label>
                <input type="password" required class="form-control" id="password" name="password" aria-describedby="emailHelp"
                       placeholder="CONTRASEÑA">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Añadir Repartidor</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/editCategoria.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>EDITAR PRODUCTO {{$categoria->id}}</h1>
        <hr>
        <form action={{route('categorias.update', $categoria->id)}} method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nombre" value='{{$categoria->nombre}}'>
                </div>
            </div>

            <button type="submit" class="btn btn-primary mb-2">Editar Categoria</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/editCliente.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>EDITAR CLIENTE {{$cliente->id}}</h1>
        <hr>
        <form action={{route('clientes.update', $cliente->id)}} method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nombre" value='{{$cliente->nombre}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Apellidos</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="apellidos" value='{{$cliente->apellidos}}'>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">EMAIL</label>
                <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp"
                       value='{{$user->email}}'>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">CONTRASEÑA</label>
                <input type="password" required class="form-control" id="password" name="password" aria-describedby="emailHelp"
                       value='{{$user->password}}'>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">DNI</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="9" minlength="9"  class="form-control" name="dni" value='{{$cliente->dni}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Direccion</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="direccion" value='{{$cliente->direccion}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Poblacion</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="poblacion" value='{{$cliente->poblacion}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Provincia</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="provincia" value='{{$cliente->provincia}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">CP</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="5" minlength="5"  class="form-control" name="cp" value='{{$cliente->cp}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Telefono</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="9" minlength="9"  class="form-control" name="telefono" value='{{$cliente->telefono}}'>
                </div>
            </div>

            <button type="submit" class="btn btn-primary mb-2">Editar Cliente</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/editProduct.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>EDITAR PRODUCTO</h1>
        <hr>
        <form action={{route('productos.update', $prod->id)}} method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nombre" value='{{$prod->nombre}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Precio</label>
                <div class="col-sm-10">
                    <input type="number" step="0.01" class="form-control" name="precio" value={{$prod['precio']}}>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Unidades</label>
                <div class="col-sm-10">
                    <input type="number" step="1" class="form-control" name="unidades" value={{$prod['unidades']}}>
                </div>
            </div>
            <div class="form-group ">
                <label for="proveedor_id">Proveedor</label>
                <select id="proveedor_id" name="proveedor_id" class="form-control">
                    @foreach ($proveedores as $proveedor)
                        @if ($proveedor->id === $prod->proveedor_id)
                            <option value= {{$proveedor->id}}  selected>{{$proveedor->nombre}}</option>
                        @else
                        <option value= {{$proveedor->id}} >{{$proveedor->nombre}} </option>
                        @endif
                    @endforeach
                </select>
            </div>
            <div class="form-group ">
                <label for="categoria_id">Categoria</label>
                <select id="categoria_id" name="categoria_id"  class="form-control">
                    @foreach ($categorias as $categoria)
                        @if($categoria->id === $prod->categoria_id)
                            <option value= {{$categoria->id}}  selected>{{$categoria->nombre}}</option>
                        @else
                        <option value= {{$categoria->id}} >{{$categoria->nombre}} </option>
                        @endif
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Editar Producto</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/editProveedor.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>EDITAR PROVEEDOR {{$proveedor->id}}</h1>
        <hr>
        <form action={{route('proveedores.update', $proveedor->id)}} method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nombre" value='{{$proveedor->nombre}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Apellidos</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="apellidos" value='{{$proveedor->apellidos}}'>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">EMAIL</label>
                <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp"
                       value='{{$proveedor->email}}'>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">NIF</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="9" class="form-control" name="nif" value='{{$proveedor->nif}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Direccion</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="direccion" value='{{$proveedor->direccion}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Poblacion</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="poblacion" value='{{$proveedor->poblacion}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Provincia</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="provincia" value='{{$proveedor->provincia}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">CP</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="5" class="form-control" name="cp" value='{{$proveedor->cp}}'>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Telefono</label>
                <div class="col-sm-10">
                    <input type="text" maxlength="9" class="form-control" name="telefono" value='{{$proveedor->telefono}}'>
                </div>
            </div>

            <button type="submit" class="btn btn-primary mb-2">Editar Proveedor</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/editRepartidor.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>EDITAR REPARTIDOR {{$repartidor->id}}</h1>
        <hr>
        <form action={{route('repartidores.update', $repartidor->id)}} method="POST">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nombre" value='{{$repartidor->nombre}}'>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">EMAIL</label>
                <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp"
                       value='{{$user->email}}'>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">CONTRASEÑA</label>
                <input type="password" required class="form-control" id="password" name="password" aria-describedby="emailHelp"
                       value='{{$user->password}}'>
            </div>

            <button type="submit" class="btn btn-primary mb-2">Editar Repartidor</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">MENU</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <a href={{ route('clientes.index')}}>Ver Clientes</a>
                        <br>
                        <a href={{ route('clientes.create')}}>Añadir Cliente</a>
                        <br>
                        <hr>
                        <a href={{ route('proveedores.index')}}>Ver Proveedores</a>
                        <br>
                        <a href={{ route('proveedores.create')}}>Añadir Proveedor</a>
                        <br>
                        <hr>
                        <a href={{ route('productos.index')}}>Ver Productos</a>
                        <br>
                        <a href={{ route('productos.create')}}>Añadir Producto</a>
                        <br>
                        <hr>
                        <a href={{ route('categorias.index')}}>Ver Categorias</a>
                        <br>
                        <a href={{ route('categorias.create')}}>Añadir Categoria</a>
                        <br>
                        <hr>
                        <a href={{ route('repartidores.index')}}>Ver Repartidores</a>
                        <br>
                        <a href={{ route('repartidores.create')}}>Añadir Repartidor</a>
                        <br>
                        <hr>
                        <a href={{ route('pedidos.index')}}>Ver Pedidos</a>
                            <br>
                            <a href={{ route('graficas')}}>Estadisticas</a>
                    </div>
                </div>
                <br>
                <div class="card-header">MANTENIMIENTO ADMIN</div>

                <div class="card-body">
                    <br>
                    <a href={{ route('editAdmin')}}>Cambiar Email</a>
                    <br>
                    <a href={{ route('editPassword')}}>Cambiar Contraseña</a>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/verCategorias.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>VER CATEGORIAS</h1>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col" class="text-center">ACCIONES</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($categorias as $categoria)
                <tr>
                    <th scope="row">{{$categoria->id}}</th>
                    <td>{{$categoria->nombre}}</td>
                    <td align="center">
                        <a title="Ver productos" href={{  route('prodCategoria', $categoria->id)}}>
                            <i class="iconify" data-icon="mdi:file-eye-outline" data-inline="false"></i>
                        </a>
                        <a title="Editar categoria" href={{  route('categorias.edit', $categoria->id)}}>
                            <i class="iconify" data-icon="mdi:square-edit-outline" data-inline="false"></i>
                        </a>
                        <a title="Eliminar categoria" onclick="return confirm('¿Quieres eliminar la categoria?')" href={{  route('delCat', $categoria->id)}}>
                            <i class="iconify" data-icon="mdi:trash-can-outline" data-inline="false"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <form action={{route('categorias.create')}} method="GET">
            <button type="submit" class="btn btn-primary mb-2">Añadir Categoria</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/verClientes.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>VER CLIENTES</h1>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DNI</th>
                <th scope="col">DIRECCION</th>
                <th scope="col">POBLACION</th>
                <th scope="col">CP</th>
                <th scope="col">PROVINCIA</th>
                <th scope="col">TELEFONO</th>
                <th scope="col" class="text-center">ACCIONES</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($clientes as $cliente)
                <tr>
                    <th scope="row">{{$cliente->id}}</th>
                    <td>{{$cliente->nombre}}</td>
                    <td>{{$cliente->apellidos}}</td>
                    <td>{{$cliente->dni}}</td>
                    <td>{{$cliente->direccion}}</td>
                    <td>{{$cliente->poblacion}}</td>
                    <td>{{$cliente->cp}}</td>
                    <td>{{$cliente->provincia}}</td>
                    <td>{{$cliente->telefono}}</td>
                    <td align="center">
                        <a title="Ver pedidos cliente" href={{  route('pedidosCliente', $cliente->id)}}}>
                            <i class="iconify" data-icon="mdi:file-eye-outline" data-inline="false"></i>
                        </a>
                        <a title="Editar cliente" href={{  route('clientes.edit', $cliente->id)}}>
                            <i class="iconify" data-icon="mdi:square-edit-outline" data-inline="false"></i>
                        </a>
                        <a title="Eliminar cliente" onclick="return confirm('¿Quieres eliminar el cliente?')" href={{  route('delCliente', $cliente->id)}}}>
                            <i class="iconify" data-icon="mdi:trash-can-outline" data-inline="false"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <form action={{route('clientes.create')}} method="GET">
            <button type="submit" class="btn btn-primary mb-2">Añadir Cliente</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/verProductos.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>VER PRODUCTOS</h1>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">PRECIO</th>
                <th scope="col">UNIDADES</th>
                <th scope="col">PROVEEDOR</th>
                <th scope="col">CATEGORIA</th>
                <th scope="col">FOTO</th>
                <th scope="col" class="text-center">ACCIONES</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($productos as $producto)
            <tr>
                <th scope="row">{{$producto->id}}</th>
                <td>{{$producto->nombre}}</td>
                <td>{{$producto->precio}} €</td>
                <td>{{$producto->unidades}} ud</td>
                <td>{{\App\Proveedor::find($producto->proveedor_id)->nombre." ".\App\Proveedor::find($producto->proveedor_id)->apellidos }}</td>
                <td>{{\App\Categoria::find($producto->categoria_id)->nombre }}</td>

                <td><img src="{{ URL::asset('storage/'.$producto->id.'/'.$producto->imagen_url) }}" height="42" width="42"/>
                    </td>
                <td align="center">
                    <a title="Editar producto" href={{  route('productos.edit', $producto->id)}}>
                        <i class="iconify" data-icon="mdi:square-edit-outline" data-inline="false"></i>
                    </a>
                    <a title="Eliminar producto" onclick="return confirm('¿Quieres eliminar el producto?')" href={{  route('delProd', $producto->id)}}>
                        <i class="iconify" data-icon="mdi:trash-can-outline" data-inline="false"></i>
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        <form action={{route('productos.create')}} method="GET">
        <button type="submit" class="btn btn-primary mb-2">Añadir Producto</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection

resources/views/verProveedores.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>VER PROVEEDORES</h1>
        <hr>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DNI</th>
                <th scope="col">DIRECCION</th>
                <th scope="col">POBLACION</th>
                <th scope="col">CP</th>
                <th scope="col">PROVINCIA</th>
                <th scope="col">TELEFONO</th>
                <th scope="col">EMAIL</th>
                <th scope="col" class="text-center">ACCIONES</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($proveedores as $proveedor)
                <tr>
                    <th scope="row">{{$proveedor->id}}</th>
                    <td>{{$proveedor->nombre}}</td>
                    <td>{{$proveedor->apellidos}}</td>
                    <td>{{$proveedor->dni}}</td>
                    <td>{{$proveedor->direccion}}</td>
                    <td>{{$proveedor->poblacion}}</td>
                    <td>{{$proveedor->cp}}</td>
                    <td>{{$proveedor->provincia}}</td>
                    <td>{{$proveedor->telefono}}</td>
                    <td>{{$proveedor->email}}</td>
                    <td align="center">
                        <a title="Ver productos" href={{  route('productosProveedor', $proveedor->id)}}>
                            <i class="iconify" data-icon="mdi:file-eye-outline" data-inline="false"></i>
                        </a>
                        <a title="Editar proveedor" href={{  route('proveedores.edit', $proveedor->id)}}>
                            <i class="iconify" data-icon="mdi:square-edit-outline" data-inline="false"></i>
                        </a>
                        <a title="Eliminar proveedor" onclick="return confirm('¿Quieres eliminar el proveedor?')" href={{  route('delProveedor', $proveedor->id)}}>
                            <i class="iconify" data-icon="mdi:trash-can-outline" data-inline="false"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <form action={{route('proveedores.create')}} method="GET">
            <button type="submit" class="btn btn-primary mb-2">Añadir Proveedor</button>
        </form>
        <hr>
        <form action={{route('home')}} method="GET">
            <button type="submit" class="btn btn-secondary mb-2">MENU</button>
        </form>
    </div>
@endsection